server.port: 7001
server.error.include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    io.locngo.learning.microservices: DEBUG
    org.springframework.data.mongodb: DEBUG
---
spring.profiles: docker

server.port: 8080

spring.data.mongodb.host: 192.168.99.100