server.port: 7003
server.error.include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:review-db
    username: user
    password: pwd
    hikari.initializationFailTimeout: 60000
  jpa:
    hibernate.ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    io.locngo.learning.microservices: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
---
spring.profiles: docker

server.port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql/review-db